local Brainrots = {
"67", "Money Money Puggy", "Agarrini la Palini", "LirilÃ¬ LarilÃ ", "Anpali Babel",
"Antonio", "Avocadini Antilopini", "Avocadini Guffo", "Avocadorilla", "Ballerina Cappuccina",
"Ballerino Lololo", "Bambini Crostini", "Bananita Dolphinita", "Bandito Axolito", "Orangutini Ananassini",
"Belula Beluga", "Bisonte Giuppitere", "Blackhole Goat", "Blueberrinni Octopusini", "Bombardini Tortinii",
"Bombardiro Crocodilo", "Bombombini Gusini", "Boneca Ambalabu", "Unclito Samito", "Gangster Footera",
"Brr es Teh Patipum", "Brri Brri Bicus Dicus Bombicus", "Brutto Gialutto", "Bulbito Bandito Traktorito", "Trulimero Trulicina",
"Cacasito Satalito", "Cacto Hipopotamo", "Capi Taco", "Matteo", "Caramello Filtrello",
"Carloo", "Carrotini Brainini", "Cavallo Virtuoso", "Celularcini Viciosini", "Chachechi",
"Chef Crabracadabra", "Chicleteira Bicicleteira", "Chihuanini Taconini", "Chimpanzini Bananini", "Cocofanto Elefanto",
"Cocosini Mama", "Crabbo Limonetta", "Dragon Cannelloni", "Dug dug dug", "Dul Dul Dul",
"Elefanto Frigo", "Esok Sekolah", "Espresso Signora", "Extinct Ballerina", "Extinct Matteo",
"Extinct Tralalero", "Orcalero Orcala", "Fragola La La La", "Frigo Camelo", "Ganganzelli Trulala",
"Garama and Madundung", "Los Tungtungtungcitos", "Gattatino Nyanino", "Gattito Tacoto", "Odin Din Din Dun",
"Glorbo Fruttodrillo", "Gorillo Subwoofero", "Gorillo Watermelondrillo", "Graipuss Medussi", "Guerriro Digitale",
"Job Job Job Sahur", "Karkerkar Kurkur", "Ketchuru and Musturu", "Ketupat Kepat", "La Cucaracha",
"La Extinct Grande", "La Grande Combinasion", "La Karkerkar Combinasion", "La Sahur Combinasion", "La Supreme Combinasion",
"La Vacca Saturno Saturnita", "Los Crocodillitos", "Las Capuchinas", "Los Tralaleritos", "Las Tralaleritas",
"Lerulerulerule", "Lionel Cactuseli", "Burbaloni Loliloli", "Los Combinasionas", "Los Hotspotsitos",
"Los Chicleteiras", "Las Vaquitas Saturnitas", "Los Noobinis", "Los Nooo My Hotspotsitos", "Girafa Celestre",
"Las Sis", "Los Matteos", "Los Tipi Tacos", "Los Orcalitos", "Los Bros",
"Los Bombinitos", "Zibra Zubra Zibralini", "Corn Corn Corn Sahur", "Malame Amarele", "Mangolini Parrocini",
"Mariachi Corazoni", "Mastodontico Telepiedone", "Fluriflura", "Urubini Flamenguini", "Noobini Pizzanini",
"Nooo My Hotspot", "Nuclearo Dinossauro", "Bandito Bobritto", "Chillin Chili", "Alessio",
"Orcalita Orcala", "Pakrahmatmamat", "Pandaccini Bananini", "Penguino Cocosino", "Perochello Lemonchello",
"Pi Pi Watermelon", "Piccione Macchina", "Piccionetta Macchina", "Pipi Avocado", "Pipi Corni",
"Pipi Kiwi", "Pipi Potato", "Pot Hotspot", "Quesadilla Crocodila", "Quivioli Ameleonni",
"Raccooni Jandelini", "Rhino Helicopterino", "Rhino Toasterino", "Salamino Penguino", "Sammyni Spyderini",
"Los Spyderinis", "Sigma Boy", "Sigma Girl", "Signore Carapace", "Spaghetti Tualetti",
"Spioniro Golubiro", "Strawberrelli Flamingelli", "Trippi Troppi", "Svinina Bombardino", "Ta Ta Ta Ta Sahur",
"Tukanno Bananno", "Tacorita Bicicleta", "Talpa Di Fero", "Tartaruga Cisterna", "Te Te Te Sahur",
"Ti Ti Ti Sahur", "Tictac Sahur", "Tigrilini Watermelini", "Tigroligre Frutonni", "Tim Cheese",
"Tipi Topi Taco", "Tirilikalika Tirilikalako", "To to to Sahur", "Tob Tobi Tobi", "Torrtuginni Dragonfrutini",
"Tracoducotulu Delapeladustuz", "Tractoro Dinosauro", "Tralaledon", "Tralalero Tralala", "Tralalita Tralala",
"Trenostruzzo Turbo 3000", "Trenostruzzo Turbo 4000", "Tric Trac Baraboom", "Trippi Troppi Troppa Trippa", "Cappuccino Assassino",
"Strawberry Elephant", "Mythic Lucky Block", "Secret Lucky Block", "Brainrot God Lucky Block", "Taco Lucky Block",
"Admin Lucky Block", "Toiletto Focaccino", "Yess my examine", "Brasilini Berimbini", "Tang Tang Keletang",
"Noo my examine", "Los Primos", "Karker Sahur", "Los Tacoritas", "Perrito Burrito",
"Brr Brr Patapim", "Pop Pop Sahur", "Los 67", "La Secret Combinasion", "Los Jobcitos",
"Los Tortus", "Burguro And Fryuro", "Bananito Bandito", "Squalanana", "Cachorrito Melonito",
"Los Lucky Blocks", "Los Karkeritos"
}
